config/routes.rb
Rails.application.routes.draw do
  resources :invoices do
    
  end
  resources :bookings do
    get 'search', on: :member
    resources :booking_details
  end

  get 'static_pages/welcome'
  get 'static_pages/help'

  root 'static_pages#welcome'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

#   resources :clients, shallow: :true do
#     resources :invoices do
#       resources :invoice_details
#       resources :invoice_payments do
#         resources :invoice_payment_details
#       end
#     end
#   end

#   resources :people, shallow: :true do
#     resources :payments do
#       resources :payment_details
#       resources :payment_extras
#     end
#   end
    resources :admin_keywords

    resources :clients, shallow: :true do
        # resources :invoices do

        # end
        resources :bookings

    end

    resources :employees, shallow: :true do

    end

end

app/models/employee.rb
class Employee < ApplicationRecord
    validates :first_name, :surname, :full_name, :address, :city, :postcode, :state, :home_phone, :mobile_phone, presence: true

    has_many :payments
    has_many :invoice_details
    has_many :b_details

    def display_name
        if self.known_as == ""
            return self.first_name + " " + self.surname
        else
            return self.known_as + " " + self.surname
        end
    end

    def display_address
        return self.address + ", " + self.city + ", " + self.state + " " + self.postcode
    end

    def current_yearly_earnings

    end

    def current_yearly_payments

    end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: [:show, :edit, :update, :destroy]

  # GET /employees
  # GET /employees.json
  def index
    @employees = Employee.all
  end

  # GET /employees/1
  # GET /employees/1.json
  def show
  end

  # GET /employees/new
  def new
    @employee = Employee.new
  end

  # GET /employees/1/edit
  def edit
  end

  # POST /employees
  # POST /employees.json
  def create
    @employee = Employee.new(employee_params)

    respond_to do |format|
      if @employee.save
        format.html { redirect_to @employee, notice: 'Employee was successfully created.' }
        format.json { render :show, status: :created, location: @employee }
      else
        format.html { render :new }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employees/1
  # PATCH/PUT /employees/1.json
  def update
    respond_to do |format|
      if @employee.update(employee_params)
        format.html { redirect_to @employee, notice: 'Employee was successfully updated.' }
        format.json { render :show, status: :ok, location: @employee }
      else
        format.html { render :edit }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1
  # DELETE /employees/1.json
  def destroy
    @employee.destroy
    respond_to do |format|
      format.html { redirect_to employees_url, notice: 'Employee was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employee
      @employee = Employee.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def employee_params
      params.require(:employee).permit(:first_name, :middle_name, :surname, :full_name, :known_as, :address, :city, :state, :postcode, :home_phone, :work_phone, :mobile_phone, :email, :birth_date, :dob_display, :superannuation_fund, :superannuation_no, :tax_file_number, :abn, :gst_registered)
    end
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/_form.html.erb
<%= form_for @employee, html: {class: "form-horizontal"} do |f| %>
  <% if @employee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

      <ul>
      <% @employee.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="action-glyphs">
    <%= f.submit "Save", class: "save btn btn-primary" %>
    <%= link_to "Cancel", employees_path, class:"btn btn-danger" %>
  </div>
  <div>
    <ul class="nav nav-tabs" style="background-color:rgba(255,255,255,0);color:rgb(255,255,255);">
      <li class="active"><a href="#employee-tab-1" role="tab" data-toggle="tab">Details </a></li>
      <li><a href="#employee-tab-2" role="tab" data-toggle="tab">Contact </a></li>
      <li><a href="#employee-tab-3" role="tab" data-toggle="tab">Financials</a></li>
    </ul>
    <div class="tab-content">
      <div class="tab-pane active" role="tabpanel" id="employee-tab-1">
        <div class="form-group" style="padding-top:10px;">
          <%= f.label :first_name, class: 'col-sm-2 control-label' %>
          <div class="col-sm-10">
            <%= f.text_field :first_name, class: 'form-control' %>
          </div>
        </div>
        <div class="form-group">
          <%= f.label :middle_name, class: 'col-sm-2 control-label' %>
          <div class="col-sm-10">
            <%= f.text_field :middle_name, class: 'form-control' %>
          </div>
        </div>
        <div class="form-group">
          <%= f.label :surname, class: 'col-sm-2 control-label' %>
          <div class="col-sm-10">
            <%= f.text_field :surname, class: 'form-control' %>
          </div>
        </div>
        <div class="form-group">
          <%= f.label :known_as, class: 'col-sm-2 control-label' %>
          <div class="col-sm-10">
            <%= f.text_field :known_as, class: 'form-control' %>
          </div>
        </div>
        <div class="form-group">
          <%= f.label :full_name, class: 'col-sm-2 control-label' %>
          <div class="col-sm-10">
            <%= f.text_field :full_name, class: 'form-control' %>
          </div>
        </div>
        <div class="form-group">
          <%= f.label :birth_date, class: 'col-sm-2 control-label' %>
          <div class="col-sm-2">
            <%= f.text_field :birth_date, hide_label: true, class: 'form-control' %>
          </div>
          <%= f.label :dob_display, class: 'col-sm-2 control-label' %>
          <div class="col-sm-2">
            <%= f.select(:dob_display, options_for_select([['Yes', true], ['No', false]], @employee.dob_display), {}, {class: 'form-control'}) %>
          </div>
        </div>
      </div>
      <div class="tab-pane" role="tabpanel" id="employee-tab-2">
        <div class="form-group" style="padding-top:10px;">
          <%= f.label :address, class: 'col-sm-2 control-label' %>
          <div class="col-sm-10">
            <%= f.text_field :address, class: 'form-control' %>
          </div>
        </div>
        <div class="form-group">
          <%= f.label :city, class: 'col-sm-2 control-label' %>
          <div class="col-sm-10">
            <%= f.text_field :city, class: 'form-control' %>
          </div>
        </div>
        <div class="form-group">
          <%= f.label :state, class: 'col-sm-2 control-label' %>
          <div class="col-sm-2">
            <%= f.select(:state, options_from_collection_for_select(AdminKeyword.where(key_type: "State"), "key_value", "key_value", @employee.state), {}, {class: 'form-control'}) %>
          </div>
          <%= f.label :postcode, class: 'col-sm-2 control-label' %>
          <div class="col-sm-2">
            <%= f.text_field :postcode, class: 'form-control' %>
          </div>
        </div>
        <div class="form-group">
          <%= f.label :home_phone, class: 'col-sm-2 control-label' %>
          <div class="col-sm-10">
            <%= f.text_field :home_phone, class: 'form-control' %>
          </div>
        </div>
        <div class="form-group">
          <%= f.label :work_phone, class: 'col-sm-2 control-label' %>
          <div class="col-sm-10">
            <%= f.text_field :work_phone, class: 'form-control' %>
          </div>
        </div>
        <div class="form-group">
          <%= f.label :mobile_phone, class: 'col-sm-2 control-label' %>
          <div class="col-sm-10">
            <%= f.text_field :mobile_phone, class: 'form-control' %>
          </div>
        </div>
        <div class="form-group">
          <%= f.label :email, class: 'col-sm-2 control-label' %>
          <div class="col-sm-10">
            <%= f.text_field :email, class: 'form-control' %>
          </div>
        </div>
      </div>
      <div class="tab-pane" role="tabpanel" id="employee-tab-3">
        <div class="form-group" style="padding-top:10px;">
          <%= f.label :superannuation_fund, class: 'col-sm-2 control-label' %>
          <div class="col-sm-10">
            <%= f.text_field :superannuation_fund, class: 'form-control' %>
          </div>
        </div>
        <div class="form-group">
          <%= f.label :superannuation_no, class: 'col-sm-2 control-label' %>
          <div class="col-sm-10">
            <%= f.text_field :superannuation_no, class: 'form-control' %>
          </div>
        </div>
        <div class="form-group">
          <%= f.label :tax_file_number, class: 'col-sm-2 control-label' %>
          <div class="col-sm-10">
            <%= f.text_field :tax_file_number, class: 'form-control' %>
          </div>
        </div>
        <div class="form-group">
          <%= f.label :abn, class: 'col-sm-2 control-label' %>
          <div class="col-sm-10">
            <%= f.text_field :abn, class: 'form-control' %>
          </div>
        </div>
        <div class="form-group">
          <%= f.label :gst_registered, class: 'col-sm-2 control-label' %>
          <div class="col-sm-2">
            <%= f.select(:gst_registered, options_for_select([['Yes', true], ['No', false]], @employee.gst_registered), {}, {class: 'form-control'}) %>
          </div>
        </div>
                    <!--<div class="form-group">-->
                        <!--<label class="control-label col-sm-2">Current YTD Earnings:</label>-->
                        <!--<div class="col-sm-10">{{ person.current_yearly_earnings }}</div>-->
                    <!--</div>-->
                    <!--<div class="form-group">-->
                        <!--<label class="control-label col-sm-2">Current YTD Payments:</label>-->
                        <!--<div class="col-sm-10">{{ person.current_yearly_payments }}</div>-->
                    <!--</div>-->
      </div>
    </div>
  </div>

<% end %>

app/views/employees/edit.html.erb
<h1>Edit Talent</h1>

<%= render 'form', employee: @employee %>

<%= link_to 'Show', @employee %> |
<%= link_to 'Back', employees_path %>

app/views/employees/index.html.erb
<h1 class="page-header">Talent</h1>
<span><%= link_to "New", new_employee_path, class: "btn btn-primary" %></span>
<div class="table-responsive">
    <table class="table table-striped" id="client-table">
        <thead>
            <tr>
                <th>Name</th>
                <th>Address</th>
                <th>Home Phone</th>
                <th>Mobile Phone</th>
                <th>Email</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            <% @employees.each do |employee| %>
                <tr>
                    <td><%= link_to employee.display_name, employee %></td>
                    <td><%= employee.display_address %></td>
                    <td><%= employee.home_phone %></td>
                    <td><%= employee.mobile_phone %></td>
                    <td><%= employee.email %></td>
                    <td><%= link_to 'Destroy', employee, method: :delete, data: { confirm: 'Are you sure?' }, class:'btn btn-xs btn-danger' %></td>
                </tr>
            <% end %>
        </tbody>
    </table>
</div>
<div class="modal fade" id="modal-client">
    <div class="modal-dialog">
        <div class="modal-content">
        </div>
    </div>
</div>

app/views/employees/new.html.erb
<h1>New Talent</h1>

<%= render 'form' %>

app/views/employees/show.html.erb
<div class='action-glyphs'>
  <span><%= link_to "Edit", edit_employee_path(@employee), class: "btn btn-primary" %></span>
  <span><%= link_to "Cancel", employees_path, class:"btn btn-danger" %></span>
</div>
<p id="notice"><%= notice %></p>
<div>
  <ul class="nav nav-tabs" style="background-color:rgba(255,255,255,0);color:rgb(255,255,255);">
    <li class="active"><a href="#employee-tab-1" role="tab" data-toggle="tab">Details </a></li>
    <li><a href="#employee-tab-2" role="tab" data-toggle="tab">Contact </a></li>
    <li><a href="#employee-tab-3" role="tab" data-toggle="tab">Financials</a></li>
  </ul>
  <div class="tab-content">
    <div class="tab-pane active" role="tabpanel" id="employee-tab-1">
      <div class="row row-buffer">
        <div class="col-sm-2"><strong>First Name:</strong></div>
        <div class="col-sm-10"><%= @employee.first_name %></div>
      </div>
      <div class="row row-buffer">
        <div class="col-sm-2"><strong>Middle Name:</strong></div>
        <div class="col-sm-10"><%= @employee.middle_name %></div>
      </div>
      <div class="row row-buffer">
        <div class="col-sm-2"><strong>Surname:</strong></div>
        <div class="col-sm-10"><%= @employee.surname %></div>
      </div>
      <div class="row row-buffer">
        <div class="col-sm-2"><strong>Known As:</strong></div>
        <div class="col-sm-10"><%= @employee.known_as %></div>
      </div>
      <div class="row row-buffer">
        <div class="col-sm-2"><strong>Full Name:</strong></div>
        <div class="col-sm-10"><%= @employee.full_name %></div>
      </div>
      <div class="row row-buffer">
        <div class="col-sm-2"><strong>Birth Date:</strong></div>
        <div class="col-sm-10"><%= @employee.birth_date.to_formatted_s(:rfc822) %></div>
      </div>
      <div class="row row-buffer">
        <div class="col-sm-2"><strong>Display DOB?</strong></div>
        <div class="col-sm-10"><%= yesno_boolean(@employee.dob_display) %></div>
      </div>
    </div>
    <div class="tab-pane" role="tabpanel" id="employee-tab-2">
      <div class="row row-buffer">
        <div class="col-sm-2"><strong>Address:</strong></div>
        <div class="col-sm-10"><%= @employee.address %></div>
      </div>
      <div class="row row-buffer">
        <div class="col-sm-2"><strong>City/Suburb:</strong></div>
        <div class="col-sm-10"><%= @employee.city %></div>
      </div>
      <div class="row row-buffer">
        <div class="col-sm-2"><strong>State:</strong></div>
        <div class="col-sm-2"><%= @employee.state %></div>
        <div class="col-sm-2"><strong>Postcode:</strong></div>
        <div class="col-sm-2"><%= @employee.postcode %></div>
      </div>
      <div class="row row-buffer">
        <div class="col-sm-2"><strong>Home Phone:</strong></div>
        <div class="col-sm-10"><%= @employee.home_phone %></div>
      </div>
      <div class="row row-buffer">
        <div class="col-sm-2"><strong>Work Phone:</strong></div>
        <div class="col-sm-10"><%= @employee.work_phone %></div>
      </div>
      <div class="row row-buffer">
        <div class="col-sm-2"><strong>Mobile Phone:</strong></div>
        <div class="col-sm-10"><%= @employee.mobile_phone %></div>
      </div>
      <div class="row row-buffer">
        <div class="col-sm-2"><strong>Email:</strong></div>
        <div class="col-sm-10"><%= @employee.email %></div>
      </div>
    </div>
    <div class="tab-pane" role="tabpanel" id="employee-tab-3">
      <div class="row row-buffer">
        <div class="col-sm-2"><strong>Superannuation Fund:</strong></div>
        <div class="col-sm-10"><%= @employee.superannuation_fund %></div>
      </div>
      <div class="row row-buffer">
        <div class="col-sm-2"><strong>Superannuation No:</strong></div>
        <div class="col-sm-10"><%= @employee.superannuation_no %></div>
      </div>
      <div class="row row-buffer">
        <div class="col-sm-2"><strong>Tax File Number:</strong></div>
        <div class="col-sm-10"><%= @employee.tax_file_number %></div>
      </div>
      <div class="row row-buffer">
        <div class="col-sm-2"><strong>ABN:</strong></div>
        <div class="col-sm-10"><%= @employee.abn %></div>
      </div>
      <div class="row row-buffer">
        <div class="col-sm-2"><strong>GST Registered?</strong></div>
        <div class="col-sm-10"><%= yesno_boolean(@employee.gst_registered) %></div>
      </div>
                  <!--<div class="row row-buffer">-->
                      <!--<label class="control-label col-sm-2">Current YTD Earnings:</label>-->
                      <!--<div class="col-sm-10">{{ person.current_yearly_earnings }}</div>-->
                  <!--</div>-->
                  <!--<div class="row row-buffer">-->
                      <!--<label class="control-label col-sm-2">Current YTD Payments:</label>-->
                      <!--<div class="col-sm-10">{{ person.current_yearly_payments }}</div>-->
                  <!--</div>-->
    </div>
  </div>