config/routes.rb
Rails.application.routes.draw do
  resources :invoices do
    
  end
  resources :bookings do
    get 'search', on: :member
    resources :booking_details
  end

  get 'static_pages/welcome'
  get 'static_pages/help'

  root 'static_pages#welcome'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

#   resources :clients, shallow: :true do
#     resources :invoices do
#       resources :invoice_details
#       resources :invoice_payments do
#         resources :invoice_payment_details
#       end
#     end
#   end

#   resources :people, shallow: :true do
#     resources :payments do
#       resources :payment_details
#       resources :payment_extras
#     end
#   end
    resources :admin_keywords

    resources :clients, shallow: :true do
        # resources :invoices do

        # end
        resources :bookings

    end

    resources :employees, shallow: :true do

    end

end

app/models/admin_keyword.rb
class AdminKeyword < ApplicationRecord
    validates :key_type, :key_value, presence: true
    
    def by_key(key)
        AdminKeyword.find_each do |keyword|
            keyword.find_by key_type: (key)    
        end
    end
end

app/controllers/admin_keywords_controller.rb
class AdminKeywordsController < ApplicationController
  before_action :set_admin_keyword, only: [:show, :edit, :update, :destroy]

  # GET /admin_keywords
  # GET /admin_keywords.json
  def index
    @keywords = AdminKeyword.all
  end

  # GET /admin_keywords/1
  # GET /admin_keywords/1.json
  def show
  end

  # GET /admin_keywords/new
  def new
    @keyword = AdminKeyword.new
  end

  # GET /admin_keywords/1/edit
  def edit
  end

  # POST /admin_keywords
  # POST /admin_keywords.json
  def create
    @keyword = AdminKeyword.new(admin_keyword_params)

    respond_to do |format|
      if @keyword.save
        format.html { redirect_to admin_keywords_url, notice: 'Keyword was successfully created.' }
        format.json { render :show, status: :created, location: @keyword }
      else
        format.html { render :new }
        format.json { render json: @keyword.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin_keywords/1
  # PATCH/PUT /admin_keywords/1.json
  def update
    respond_to do |format|
      if @keyword.update(admin_keyword_params)
        format.html { redirect_to @keyword, notice: 'Keyword was successfully updated.' }
        format.json { render :show, status: :ok, location: @keyword }
      else
        format.html { render :edit }
        format.json { render json: @keyword.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin_keywords/1
  # DELETE /admin_keywords/1.json
  def destroy
    @keyword.destroy
    respond_to do |format|
      format.html { redirect_to admin_keywords_url, notice: 'Keyword was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_keyword
      @keyword = AdminKeyword.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_keyword_params
      params.require(:admin_keyword).permit(:key_type, :key_subtype, :key_value)
    end
end

app/helpers/admin_keywords_helper.rb
module AdminKeywordsHelper
end

app/views/admin_keywords/_form.html.erb
<%= form_for @keyword, html: {class: "form-horizontal"} do |f| %>
    <% if @keyword.errors.any? %>
        <div id="error_explanation">
            <h2><%= pluralize(@keyword.errors.count, "error") %> prohibited this keyword from being saved:</h2>
            <ul>
                <% @keyword.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                <% end %>
            </ul>
        </div>
    <% end %>
    <div class="action-glyphs">
        <%= f.submit "Save", class: "save btn btn-primary" %>
        <%= link_to "Cancel", admin_keywords_path, class:"btn btn-danger" %>
    </div>
    <div class="panel panel-primary">
        <div class="panel-heading">
            <h3 class="panel-title">Keyword</h3></div>
            <div class="panel-body">
                <div class="form-group">
                    <%= f.label :type, class: 'col-sm-2 control-label' %>
                    <div class="col-sm-10">
                        <%= f.text_field :key_type, class: 'form-control' %>
                    </div>
                </div>
                <div class="form-group">
                    <%= f.label :subtype, class: 'col-sm-2 control-label' %>
                    <div class="col-sm-10">
                        <%= f.text_field :key_subtype, class: 'form-control' %>
                    </div>
                </div>
                <div class="form-group">
                    <%= f.label :value, class: 'col-sm-2 control-label' %>
                    <div class="col-sm-10">
                        <%= f.text_field :key_value, class: 'form-control' %>
                    </div>
                </div>
            </div>
        </div>
    </div>
<% end %>

app/views/admin_keywords/edit.html.erb
<h1>Edit Keyword</h1>

<%= render 'form' %>

app/views/admin_keywords/index.html.erb
<h1 class="page-header">Administration - Keywords</h1>
<span><%= link_to "New", new_admin_keyword_path, class: "btn btn-primary" %></span>
<div class="table-responsive">
    <table class="table table-striped" id="keyword-table">
        <thead>
            <tr>
                <th>Type</th>
                <th>Subtype</th>
                <th>Value</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            <% @keywords.order(key_type: :asc, key_subtype: :asc, key_value: :asc).each do |keyword| %>
                <tr>
                    <td><%= link_to keyword.key_type, keyword %></td>
                    <td><%= keyword.key_subtype %></td>
                    <td><%= keyword.key_value %></td>
                    <td><%= link_to 'Destroy', keyword, method: :delete, data: { confirm: 'Are you sure?' }, class:'btn btn-xs btn-danger' %></td>
                </tr>
            <% end %>
        </tbody>
    </table>
</div>
<!--<div class="modal fade" id="modal-client">-->
<!--    <div class="modal-dialog">-->
<!--        <div class="modal-content">-->
<!--        </div>-->
<!--    </div>-->
<!--</div>-->

app/views/admin_keywords/new.html.erb
<h1>New Keyword</h1>

<%= render 'form' %>

app/views/admin_keywords/show.html.erb
<div class='action-glyphs'>
  <span><%= link_to "Edit", edit_admin_keyword_path(@keyword), class: "btn btn-primary" %></span>
  <span><%= link_to "Cancel", admin_keywords_path, class:"btn btn-danger" %></span>
</div>
<p id="notice"><%= notice %></p>
<div class="panel panel-primary">
  <div class="panel-heading">
    <h3 class="panel-title">Keyword</h3>
  </div>
  <div class="panel-body">
    <div class="row row-buffer">
      <div class="col-sm-2"><strong>Type:</strong></div>
      <div class="col-sm-10"><%= @keyword.key_type %></div>
    </div>
    <div class="row row-buffer">
      <div class="col-sm-2"><strong>Subtype:</strong></div>
      <div class="col-sm-10"><%= @keyword.key_subtype %></div>
    </div>
    <div class="row row-buffer">
      <div class="col-sm-2"><strong>Value:</strong></div>
      <div class="col-sm-10"><%= @keyword.key_value %></div>
    </div>
  </div>
</div>