config/routes.rb
Rails.application.routes.draw do
  resources :invoices do
    
  end
  resources :bookings do
    get 'search', on: :member
    resources :booking_details
  end

  get 'static_pages/welcome'
  get 'static_pages/help'

  root 'static_pages#welcome'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

#   resources :clients, shallow: :true do
#     resources :invoices do
#       resources :invoice_details
#       resources :invoice_payments do
#         resources :invoice_payment_details
#       end
#     end
#   end

#   resources :people, shallow: :true do
#     resources :payments do
#       resources :payment_details
#       resources :payment_extras
#     end
#   end
    resources :admin_keywords

    resources :clients, shallow: :true do
        # resources :invoices do

        # end
        resources :bookings

    end

    resources :employees, shallow: :true do

    end

end

app/models/invoice.rb
class Invoice < ApplicationRecord
  validates :invoice_ref, :invoice_date, :client_id, :booking_id, :super_total, :gst_included, :invoice_total, presence: :true

  has_many :invoice_details, dependent: :destroy
  belongs_to :client
  belongs_to :booking

  accepts_nested_attributes_for :invoice_details
  
  def client_name
    if self.client_id != "" then
      return Client.find(self.client_id).client_name
    end
  end
  def booking_ref
    if self.booking_id != "" then
      return Booking.find(self.booking_id).booking_ref
    end
  end
  def booking_date
    if self.booking_id != "" then
      return Booking.find(self.booking_id).start_date
    end
  end
  def booking_desc
    if self.booking_id != "" then
      return Booking.find(self.booking_id).description
    end
  end

end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
  before_action :set_invoice, only: [:show, :edit, :update, :destroy]

  # GET /invoices
  # GET /invoices.json
  def index
    @invoices = Invoice.all
  end

  # GET /invoices/1
  # GET /invoices/1.json
  def show
  end

  # GET /invoices/new
  def new
    @invoice = Invoice.new
    @bookings = Booking.all
    @employees = Employee.all
    @invoice.invoice_details.build
  end

  # GET /invoices/1/edit
  def edit
    @invoice = Invoice.find(params[:id])
    @bookings = Booking.all
    @invoice_details= @invoice.invoice_details
  end

  # POST /invoices
  # POST /invoices.json
  def create
    @invoice = Invoice.new(invoice_params)
    @invoice.client_id = Booking.find_by(params[:booking_id]).client_id

    respond_to do |format|
      if @invoice.save
        format.html { redirect_to @invoice, notice: 'Invoice was successfully created.' }
        format.json { render :show, status: :created, location: @invoice }
      else
        format.html { render :new }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /invoices/1
  # PATCH/PUT /invoices/1.json
  def update
    respond_to do |format|
      if @invoice.update(invoice_params)
        format.html { redirect_to @invoice, notice: 'Invoice was successfully updated.' }
        format.json { render :show, status: :ok, location: @invoice }
      else
        format.html { render :edit }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /invoices/1
  # DELETE /invoices/1.json
  def destroy
    @invoice.destroy
    respond_to do |format|
      format.html { redirect_to invoices_url, notice: 'Invoice was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_invoice
      @invoice = Invoice.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def invoice_params
      params.require(:invoice).permit(:invoice_ref, :invoice_date, :client_id, :booking_id, :super_total, :service_fee, :gst_included, :gst_service_fee, :gst_invoice, :invoice_currency, :invoice_total, :print_flag, :paid_flag, :current_gross, :current_gst, invoice_details_attributes: [:id, :employee_id, :gross_total, :employee_total, :commission, :taxable_amount, :gst_employee, :super, :tax, :commission_gst, :paid_flag
])
    end
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/views/invoices/_detail_fields.html.erb
<div class="col-sm-3">
  <%= f.select(:employee_id, options_from_collection_for_select(@employees, "id", "display_name", ""), {include_blank: true}, {class: 'form-control'}) %>
</div>
<div class="col-sm-1">
  <%= f.text_field :gross_total, class: 'form-control' %>
</div>
<div class="col-sm-1">
  <%= f.text_field :employee_total, class: 'form-control' %>
</div>
<div class="col-sm-1">
  <%= f.text_field :taxable_amount, class: 'form-control' %>
</div>
<div class="col-sm-1">
  <%= f.text_field :commission, class: 'form-control' %>
</div>
<div class="col-sm-1">
  <%= f.text_field :gst_employee, class: 'form-control' %>
</div>
<div class="col-sm-1">
  <%= f.text_field :super, class: 'form-control' %>
</div>
<div class="col-sm-1">
  <%= f.text_field :tax, class: 'form-control' %>
</div>
<div class="col-sm-1" style="padding-bottom:10px;">
  <%= f.text_field :commission_gst, class: 'form-control' %>
</div>
<div class="col-sm-1">
  <%= link_to_remove_association 'Remove', f, class: 'btn btn-xs btn-danger' %>
</div>

app/views/invoices/_form-bkp.html.erb
<%= form_for @invoice do |f| %>
  <% if invoice.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@booking.errors.count, "error") %> prohibited this invoice from being saved:</h2>

    <ul>
    <% @invoice.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
  <% end %>

  <div class="action-glyphs">
      <%= f.submit "Save", class: "save btn btn-primary" %>
      <%= link_to "Cancel", invoices_path, class:"btn btn-danger" %>
  </div>
  <div class="panel-group">
    <div class="panel panel-primary">
      <div class="panel-heading">Invoice Details</div>
      <div class="panel-body">
        <div class="form-group" style="padding-bottom:30px;">
          <%= f.label :invoice_ref, class: 'col-sm-2 control-label' %>
          <div class="col-sm-4">
              <%= f.text_field :invoice_ref, class: 'form-control' %>
          </div>
          <%= f.label :invoice_date, class: 'col-sm-2 control-label' %>
          <div class="col-sm-4">
            <%= f.text_field :invoice_date, hide_label: true, class: 'form-control', data:{ provide:'datepicker', date_format: 'dd/mm/yyyy' } %>
          </div>
        </div>
        <div class="form-group" style="padding-bottom:30px;">
          <%= f.label :booking_id, "Booking", class: 'col-sm-2 control-label' %>
          <div class="col-sm-4">
              <%= f.select(:booking_id, options_from_collection_for_select(@bookings, "id", "booking_ref", @invoice.booking_id), {}, {class: 'form-control'}) %>
          </div>
          <%= f.label "Client", class: 'col-sm-2 control-label' %>
          <div class="col-sm-4">
              <div class='form-control-static' id='dspClientName'>
          </div>
        </div>
        <div class="form-group" style="padding-bottom:30px;">
          <%= f.label "Booking date", class: 'col-sm-2 control-label' %>
          <div class="col-sm-2">
            <div class='form-control-static' id='dspBookingDate'>
          </div>
          <%= f.label "Details", class: 'col-sm-2 control-label' %>
          <div class="col-sm-6">
            <div class='form-control-static' id='dspDescription'>
          </div>
        </div>
        <div class="form-group" style="padding-bottom:30px;">
          <%= f.label :invoice_currency, class: 'col-sm-2 control-label' %>
          <div class="col-sm-3">
            <%= f.select(:invoice_currency, options_from_collection_for_select(AdminKeyword.where(key_type: "Currency"), "key_value", "key_value", @invoice.invoice_currency), {}, {class: 'form-control'}) %>
          </div>
          <%= f.label :invoice_total, "Details", class: 'col-sm-2 control-label' %>
          <div class="col-sm-3">
            <%= f.text_field :invoice_total, class: 'form-control' %>
          </div>
        </div>
        <div class="form-group" style="padding-bottom:30px;">
          <%= f.label :super_total, class: 'col-sm-2 control-label' %>
          <div class="col-sm-3">
            <%= f.text_field :super_total, class: 'form-control' %>
          </div>
          <%= f.label :service_fee, "Details", class: 'col-sm-2 control-label' %>
          <div class="col-sm-3">
            <%= f.text_field :service_fee, class: 'form-control' %>
          </div>
        </div>
        <div class="form-group" style="padding-bottom:30px;">
          <%= f.label :gst_included, class: 'col-sm-2 control-label' %>
          <div class="col-sm-2">
            <%= f.select(:gst_included, options_for_select([['Yes', true], ['No', false]], @invoice.gst_included), {}, {class: 'form-control'}) %>
          </div>
          <%= f.label :gst_invoice, class: 'col-sm-2 control-label' %>
          <div class="col-sm-3">
            <%= f.text_field :gst_invoice, class: 'form-control' %>
          </div>
          <%= f.label :gst_service_fee, class: 'col-sm-2 control-label' %>
          <div class="col-sm-3">
            <%= f.text_field :gst_service_fee, class: 'form-control' %>
          </div>
        </div>
        <!-- <div class="panel panel-default">
          <div class="panel-body">
            <div class="col-sm-2">Name</div>
            <div class="col-sm-2">Start</div>
            <div class="col-sm-2">End</div>
            <div class="col-sm-1">Duration</div>
            <div class="col-sm-4">Notes</div>
            <div class="col-sm-1"><%= link_to_add_association 'Add Details', f, :booking_details, partial: 'bookings/detail_fields', class: 'btn btn-sm btn-primary', data: { association_insertion_method: :append,  association_insertion_node: '#detail_body'} %></div>
            <hr />
            <div id="detail_body">
            <%= f.fields_for :booking_details do |dtl| %>
              <%= render 'detail_fields', :f => dtl %>
            <% end %>
            </div>
          </div>
        </div> -->
      </div>
    </div>
  </div>
  <div class="field">
    <%= form.label :invoice_ref %>
    <%= form.text_field :invoice_ref, id: :invoice_invoice_ref %>
  </div>

  <div class="field">
    <%= form.label :invoice_date %>
    <%= form.date_select :invoice_date, id: :invoice_invoice_date %>
  </div>

  <div class="field">
    <%= form.label :client_id %>
    <%= form.text_field :client_id, id: :invoice_client_id %>
  </div>

  <div class="field">
    <%= form.label :booking_id %>
    <%= form.text_field :booking_id, id: :invoice_booking_id %>
  </div>

  <div class="field">
    <%= form.label :super_total %>
    <%= form.text_field :super_total, id: :invoice_super_total %>
  </div>

  <div class="field">
    <%= form.label :service_fee %>
    <%= form.text_field :service_fee, id: :invoice_service_fee %>
  </div>

  <div class="field">
    <%= form.label :gst_included %>
    <%= form.check_box :gst_included, id: :invoice_gst_included %>
  </div>

  <div class="field">
    <%= form.label :gst_service_fee %>
    <%= form.text_field :gst_service_fee, id: :invoice_gst_service_fee %>
  </div>

  <div class="field">
    <%= form.label :gst_invoice %>
    <%= form.text_field :gst_invoice, id: :invoice_gst_invoice %>
  </div>

  <div class="field">
    <%= form.label :invoice_currency %>
    <%= form.text_field :invoice_currency, id: :invoice_invoice_currency %>
  </div>

  <div class="field">
    <%= form.label :invoice_total %>
    <%= form.text_field :invoice_total, id: :invoice_invoice_total %>
  </div>

  <div class="field">
    <%= form.label :print_flag %>
    <%= form.check_box :print_flag, id: :invoice_print_flag %>
  </div>

  <div class="field">
    <%= form.label :paid_flag %>
    <%= form.check_box :paid_flag, id: :invoice_paid_flag %>
  </div>

  <div class="field">
    <%= form.label :current_gross %>
    <%= form.text_field :current_gross, id: :invoice_current_gross %>
  </div>

  <div class="field">
    <%= form.label :current_gst %>
    <%= form.text_field :current_gst, id: :invoice_current_gst %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/invoices/_form.html.erb
<%= form_for @invoice do |f| %>
  <% if invoice.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@invoice.errors.count, "error") %> prohibited this invoice from being saved:</h2>

    <ul>
    <% @invoice.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
  <% end %>

  <div class="action-glyphs">
      <%= f.submit "Save", class: "save btn btn-primary" %>
      <%= link_to "Cancel", invoices_path, class:"btn btn-danger" %>
  </div>
  <div class="panel-group">
    <div class="panel panel-primary">
      <div class="panel-heading">Invoice Details</div>
      <div class="panel-body">
        <div class="form-group" style="padding-bottom:30px;">
          <%= f.label :invoice_ref, class: 'col-sm-2 control-label' %>
          <div class="col-sm-2">
              <%= f.text_field :invoice_ref, class: 'form-control' %>
          </div>
          <%= f.label :invoice_date, class: 'col-sm-2 control-label' %>
          <div class="col-sm-2">
            <%= f.text_field :invoice_date, hide_label: true, class: 'form-control', data:{ provide:'datepicker', date_format: 'dd/mm/yyyy' } %>
          </div>
        </div>
        <div class="form-group" style="padding-bottom:30px;">
          <%= f.label :booking_id, "Booking", class: 'col-sm-2 control-label' %>
          <div class="col-sm-2">
              <%= f.select(:booking_id, options_from_collection_for_select(@bookings, "id", "booking_ref", @invoice.booking_id), {include_blank: true}, {class: 'form-control'}) %>
          </div>
          <%= f.label "Client", class: 'col-sm-2 control-label' %>
          <div class="col-sm-2">
              <div class='form-control-static' id='dspClientName'></div>
          </div>
        </div>
        <div class="form-group" style="padding-bottom:30px;">
          <%= f.label "Booking date", class: 'col-sm-2 control-label' %>
          <div class="col-sm-2">
            <div class='form-control-static' id='dspBookingDate'></div>
          </div>
          <%= f.label "Details", class: 'col-sm-2 control-label' %>
          <div class="col-sm-4">
            <div class='form-control-static' id='dspDescription'></div>
          </div>
        </div>
        <div class="form-group" style="padding-bottom:30px;">
          <%= f.label :invoice_currency, class: 'col-sm-2 control-label' %>
          <div class="col-sm-2">
            <%= f.select(:invoice_currency, options_from_collection_for_select(AdminKeyword.where(key_type: "Currency"), "key_value", "key_value", @invoice.invoice_currency), {}, {class: 'form-control'}) %>
          </div>
          <%= f.label :invoice_total, class: 'col-sm-2 control-label' %>
          <div class="col-sm-2">
            <%= f.text_field :invoice_total, class: 'form-control' %>
          </div>
        </div>
        <div class="form-group" style="padding-bottom:30px;">
          <%= f.label :super_total, class: 'col-sm-2 control-label' %>
          <div class="col-sm-2">
            <%= f.text_field :super_total, class: 'form-control' %>
          </div>
          <%= f.label :service_fee, class: 'col-sm-2 control-label' %>
          <div class="col-sm-2">
            <%= f.text_field :service_fee, class: 'form-control' %>
          </div>
        </div>
        <div class="form-group" style="padding-bottom:30px;">
          <%= f.label :gst_included, class: 'col-sm-2 control-label' %>
          <div class="col-sm-2">
            <%= f.select(:gst_included, options_for_select([['Yes', true], ['No', false]], @invoice.gst_included), {}, {class: 'form-control'}) %>
          </div>
        </div>
        <div class="form-group" style="padding-bottom:30px;">
          <%= f.label :gst_invoice, class: 'col-sm-2 control-label' %>
          <div class="col-sm-2">
            <%= f.text_field :gst_invoice, class: 'form-control' %>
          </div>
          <%= f.label :gst_service_fee, class: 'col-sm-2 control-label' %>
          <div class="col-sm-2">
            <%= f.text_field :gst_service_fee, class: 'form-control' %>
          </div>
        </div>
        <div class="panel panel-default">
          <div class="panel-body">
            <div class="col-sm-3">Employee</div>
            <div class="col-sm-1">Gross Amt</div>
            <div class="col-sm-1">Employee Amt</div>
            <div class="col-sm-1">Taxable Amt</div>
            <div class="col-sm-1">Commission</div>
            <div class="col-sm-1">GST Amt</div>
            <div class="col-sm-1">Superannuation</div>
            <div class="col-sm-1">PAYE Amt</div>
            <div class="col-sm-1">GST Commission</div>
            <div class="col-sm-1"><%= link_to_add_association 'Add Details', f, :invoice_details, partial: 'invoices/detail_fields', class: 'btn btn-sm btn-primary', data: { association_insertion_method: :append,  association_insertion_node: '#detail_body'} %></div>
            <hr />
            <div id="detail_body">
              <%= f.fields_for :invoice_details do |dtl| %>
                <%= render 'detail_fields', :f => dtl %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/invoices/edit.html.erb
<h1>Editing Invoice</h1>

<%= render 'form', invoice: @invoice %>

<%= link_to 'Show', @invoice %> |
<%= link_to 'Back', invoices_path %>

app/views/invoices/index.html.erb
<h1 class="page-header">Invoices</h1>
<span><%= link_to "New", new_invoice_path, class: "btn btn-primary" %></span>
<div class="table-responsive">
    <table class="table table-striped" id="invoice-table">
        <thead>
            <tr>
                <th>Invoice #</th>
                <th>Date</th>
                <th>Client</th>
                <th>Booking #</th>
                <th>Invoice Total</th>
                <th>Paid</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            <% @invoices.each do |invoice| %>
                <tr>
                    <td><%= link_to invoice.invoice_ref, invoice %></td>
                    <td><%= invoice.invoice_date.to_formatted_s(:rfc822) %></td>
                    <td><%= invoice.booking_id.client_name %></td>
                    <td><%= invoice.booking_id.booking_ref %></td>
                    <td><%= invoice.invoice_total %></td>
                    <td><%= invoice.paid_flag %></td>
                    <td><%= link_to 'Destroy', invoice, method: :delete, data: { confirm: 'Are you sure?' }, class:'btn btn-xs btn-danger' %></td>
                </tr>
            <% end %>
        </tbody>
    </table>
</div>
<div class="modal fade" id="modal-invoice">
    <div class="modal-dialog">
        <div class="modal-content">
        </div>
    </div>
</div>

app/views/invoices/new.html.erb
<h1>New Invoice</h1>

<%= render 'form', invoice: @invoice %>

<%= link_to 'Back', invoices_path %>

app/views/invoices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Invoice ref:</strong>
  <%= @invoice.invoice_ref %>
</p>

<p>
  <strong>Invoice date:</strong>
  <%= @invoice.invoice_date %>
</p>

<p>
  <strong>Client:</strong>
  <%= @invoice.client %>
</p>

<p>
  <strong>Booking:</strong>
  <%= @invoice.booking %>
</p>

<p>
  <strong>Super total:</strong>
  <%= @invoice.super_total %>
</p>

<p>
  <strong>Service fee:</strong>
  <%= @invoice.service_fee %>
</p>

<p>
  <strong>Gst included:</strong>
  <%= @invoice.gst_included %>
</p>

<p>
  <strong>Gst service fee:</strong>
  <%= @invoice.gst_service_fee %>
</p>

<p>
  <strong>Gst invoice:</strong>
  <%= @invoice.gst_invoice %>
</p>

<p>
  <strong>Invoice currency:</strong>
  <%= @invoice.invoice_currency %>
</p>

<p>
  <strong>Invoice total:</strong>
  <%= @invoice.invoice_total %>
</p>

<p>
  <strong>Print flag:</strong>
  <%= @invoice.print_flag %>
</p>

<p>
  <strong>Paid flag:</strong>
  <%= @invoice.paid_flag %>
</p>

<p>
  <strong>Current gross:</strong>
  <%= @invoice.current_gross %>
</p>

<p>
  <strong>Current gst:</strong>
  <%= @invoice.current_gst %>
</p>

<%= link_to 'Edit', edit_invoice_path(@invoice) %> |
<%= link_to 'Back', invoices_path %>