config/routes.rb
Rails.application.routes.draw do
  resources :invoices do
    
  end
  resources :bookings do
    get 'search', on: :member
    resources :booking_details
  end

  get 'static_pages/welcome'
  get 'static_pages/help'

  root 'static_pages#welcome'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

#   resources :clients, shallow: :true do
#     resources :invoices do
#       resources :invoice_details
#       resources :invoice_payments do
#         resources :invoice_payment_details
#       end
#     end
#   end

#   resources :people, shallow: :true do
#     resources :payments do
#       resources :payment_details
#       resources :payment_extras
#     end
#   end
    resources :admin_keywords

    resources :clients, shallow: :true do
        # resources :invoices do

        # end
        resources :bookings

    end

    resources :employees, shallow: :true do

    end

end

app/models/admin_keyword.rb
class AdminKeyword < ApplicationRecord
    validates :key_type, :key_value, presence: true
    
    def by_key(key)
        AdminKeyword.find_each do |keyword|
            keyword.find_by key_type: (key)    
        end
    end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  validates :booking_ref, :start_date, :end_date, :description, :duration, :client_id, presence: true
  
  has_many :booking_details, dependent: :destroy
  belongs_to :client

  accepts_nested_attributes_for :booking_details

  def client_name
    if self.client_id != "" then
      return Client.find(self.client_id).client_name
    end
  end
end

app/models/booking_detail.rb
class BookingDetail < ApplicationRecord
  validates :start_date, :end_date, :notes, :duration, :employee_id, presence: true
  belongs_to :booking
  belongs_to :employee

  def employee_name
    if self.employee_id != "" then
      @employee = Employee.find(self.employee_id)
      return @employee.display_name
    end
  end
end

app/models/client.rb
class Client < ApplicationRecord
   validates :client_name, :street_address, :street_city, :street_state, :street_postcode, :contact_name, :contact_email, :contact_phone, :client_abn, presence: true

   has_many :invoice_payments
   has_many :invoices
   has_many :bookings

   def display_address
     if self.street_address != nil then
       return self.street_address + ", " + self.street_city + ", " + self.street_state + ", " + self.street_postcode
     end
   end
   def display_post_address
     if self.postal_address != nil then
       return self.postal_address + ", " + self.postal_city + ", " + self.postal_state + ", " + self.postal_postcode
     end
   end

end

app/models/employee.rb
class Employee < ApplicationRecord
    validates :first_name, :surname, :full_name, :address, :city, :postcode, :state, :home_phone, :mobile_phone, presence: true

    has_many :payments
    has_many :invoice_details
    has_many :b_details

    def display_name
        if self.known_as == ""
            return self.first_name + " " + self.surname
        else
            return self.known_as + " " + self.surname
        end
    end

    def display_address
        return self.address + ", " + self.city + ", " + self.state + " " + self.postcode
    end

    def current_yearly_earnings

    end

    def current_yearly_payments

    end
end

app/models/invoice.rb
class Invoice < ApplicationRecord
  validates :invoice_ref, :invoice_date, :client_id, :booking_id, :super_total, :gst_included, :invoice_total, presence: :true

  has_many :invoice_details, dependent: :destroy
  belongs_to :client
  belongs_to :booking

  accepts_nested_attributes_for :invoice_details
  
  def client_name
    if self.client_id != "" then
      return Client.find(self.client_id).client_name
    end
  end
  def booking_ref
    if self.booking_id != "" then
      return Booking.find(self.booking_id).booking_ref
    end
  end
  def booking_date
    if self.booking_id != "" then
      return Booking.find(self.booking_id).start_date
    end
  end
  def booking_desc
    if self.booking_id != "" then
      return Booking.find(self.booking_id).description
    end
  end

end

app/models/invoice_detail.rb
class InvoiceDetail < ApplicationRecord
  validates :invoice_id, :gross_total, :employee_total, presence: true

  belongs_to :invoice
  belongs_to :employee

  
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: [:show, :edit, :update, :destroy]

  # GET /clients
  # GET /clients.json
  def index
    @clients = Client.all
  end

  # GET /clients/1
  # GET /clients/1.json
  def show
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients
  # POST /clients.json
  def create
    @client = Client.new(client_params)

    respond_to do |format|
      if @client.save
        format.html { redirect_to @client, notice: 'Client was successfully created.' }
        format.json { render :show, status: :created, location: @client }
      else
        format.html { render :new }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1
  # PATCH/PUT /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to @client, notice: 'Client was successfully updated.' }
        format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1
  # DELETE /clients/1.json
  def destroy
    @client.destroy
    respond_to do |format|
      format.html { redirect_to clients_url, notice: 'Client was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def client_params
      params.require(:client).permit(:client_name, :street_address, :street_city, :street_state, :street_postcode, :postal_address, :postal_city, :postal_state, :postal_postcode, :contact_name, :contact_phone, :contact_fax, :contact_email, :client_tax, :client_super, :client_abn, :client_terms)
    end
end

app/helpers/admin_keywords_helper.rb
module AdminKeywordsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

    def yesno_boolean(boolean)
        boolean ? 'Yes' : 'No'
    end

end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/form_helper.rb
module FormHelper
end

app/helpers/hotels_helper.rb
module HotelsHelper
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/room_categories_helper.rb
module RoomCategoriesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">TIPS</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Dashboard</a></li>
        <li><a href="#">Settings</a></li>
        <li><a href="#">Profile</a></li>
        <li><a href="#">Help</a></li>
      </ul>
      <form class="navbar-form navbar-right">
        <input type="text" class="form-control" placeholder="Search...">
      </form>
    </div>
  </div>
</nav>

app/views/layouts/_sidebar.html.erb
<div class="col-sm-3 col-md-2 sidebar">
  <ul class="nav nav-sidebar">
    <li class="active"><%= link_to "Clients", clients_path %></li>
    <li><%= link_to "Talent", employees_path %></li>
  </ul>
  <ul class="nav nav-sidebar">
    <li><a href=""><%= link_to "Bookings", bookings_path %></a></li>
    <li><a href="">Invoices</a></li>
    <li><a href="">Payments</a></li>
    <li><a href="">Talent Payments</a></li>
  </ul>
  <ul class="nav nav-sidebar">
    <li><a href="">Reports</a></li>
  </ul>
  <ul class="nav nav-sidebar">
    <li><%= link_to "Administration - Keywords", admin_keywords_path %></li>
  </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>rubyTIPS</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container-fluid">
      <div class="row" style="padding-top: 50px;">
        <%= render 'layouts/sidebar' %>
        <div class="col-sm-9 col-md-10 main">
          <div class="container-fluid">
            <%= yield %>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>